/** Auto-generated by scripts/build-puzzle-catalog.mjs — do not edit by hand */

export const PUZZLE_CATALOG_ENTRIES = [
  {
    "weekIndex": 1,
    "difficulty": "easy",
    "estimatedRating": 1350,
    "fen": "6k1/5ppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "f7"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f7",
                  "to": "f8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: dáma zoberie na f7, po Kh8 dorazte na f8.",
    "solution": "Qxf7+ Kh8 Qf8#"
  },
  {
    "weekIndex": 1,
    "difficulty": "medium",
    "estimatedRating": 1550,
    "fen": "6k1/5ppp/8/8/8/5N2/5QPP/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "e1"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e1",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qe1+ a po ustúpení kráľa mat na e8.",
    "solution": "Qe1+ Kh8 Qe8#"
  },
  {
    "weekIndex": 1,
    "difficulty": "hard",
    "estimatedRating": 1850,
    "fen": "6k1/8/8/4N3/5q2/8/8/2R3K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "c1",
          "to": "c8"
        },
        "wrong": "Začnite šachom podľa plánu úlohy.",
        "accept": "check"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f4",
              "to": "f8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c8",
                  "to": "f8"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Taktika v troch ťahoch: šach vežou, zoberte prekrývajúcu dámu.",
    "solution": "Rc8+ Qf8 Rxf8"
  },
  {
    "weekIndex": 2,
    "difficulty": "easy",
    "estimatedRating": 1382,
    "fen": "5qk1/5ppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "f7"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f7",
                  "to": "f8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: útok na f7 aj s čiernou dámou na diagonále.",
    "solution": "Qxf7+ Kh8 Qxf8#"
  },
  {
    "weekIndex": 2,
    "difficulty": "medium",
    "estimatedRating": 1593,
    "fen": "6k1/5ppp/8/8/8/8/4Q2R/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "e2",
          "to": "d3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "d3",
                  "to": "d8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qd3+ a mat na d8, veža na h2.",
    "solution": "Qd3+ Kh8 Qd8#"
  },
  {
    "weekIndex": 2,
    "difficulty": "hard",
    "estimatedRating": 1905,
    "fen": "2r1k3/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b7"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f2",
                  "to": "f7"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Dvojná útok vežou na b7, po Rd8 rozhodujúci mat dámou.",
    "solution": "Rb7 Rd8 Qxf7#"
  },
  {
    "weekIndex": 3,
    "difficulty": "easy",
    "estimatedRating": 1414,
    "fen": "6k1/5ppp/8/8/8/8/6R1/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "g2",
          "to": "e2"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e2",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: veža na e2, potom mat na e8.",
    "solution": "Re2+ Kh8 Re8#"
  },
  {
    "weekIndex": 3,
    "difficulty": "medium",
    "estimatedRating": 1635,
    "fen": "2r1k3/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b7"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "e8",
                      "to": "f8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "f2",
                          "to": "f7"
                        },
                        "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                        "accept": "checkmate"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Kombinácia veže na b4–b7, potom mat dámou na f7.",
    "solution": "Rb4 Rd8 Rb7+ Kf8 Qxf7#"
  },
  {
    "weekIndex": 3,
    "difficulty": "hard",
    "estimatedRating": 1959,
    "fen": "2r1k3/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b5"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "d8",
                      "to": "d7"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "b5",
                          "to": "b7"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "d7",
                              "to": "d8"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "f2",
                                  "to": "f7"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Štvorťahová kombinácia: veža obchádza obranu na d7, finiš Qxf7#.",
    "solution": "Rb4 Rd8 Rb5 Rd7 Rb7 Rd8 Qxf7#"
  },
  {
    "weekIndex": 4,
    "difficulty": "easy",
    "estimatedRating": 1445,
    "fen": "6k1/5ppp/8/8/8/8/R7/4K3 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "a2",
          "to": "a3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "a3",
                  "to": "a8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: veža cez a3 na a8.",
    "solution": "Ra3+ Kh8 Ra8#"
  },
  {
    "weekIndex": 4,
    "difficulty": "medium",
    "estimatedRating": 1678,
    "fen": "6k1/5ppp/8/8/8/8/2Q5/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "c2",
          "to": "b3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b3",
                  "to": "b8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: dáma na b3 a finiš na b8.",
    "solution": "Qb3+ Kh8 Qb8#"
  },
  {
    "weekIndex": 4,
    "difficulty": "hard",
    "estimatedRating": 2014,
    "fen": "2r2k2/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b5"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "d8",
                      "to": "e8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "b5",
                          "to": "b7"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "e8",
                              "to": "e6"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "f2",
                                  "to": "f7"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Zložitejšia vežová kombinácia s finišom dámou na f7.",
    "solution": "Rb4 Rd8 Rb5 Re8 Rb7 Re6 Qxf7#"
  },
  {
    "weekIndex": 5,
    "difficulty": "easy",
    "estimatedRating": 1477,
    "fen": "6k1/5ppp/8/8/8/8/1R6/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b2",
          "to": "b3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b3",
                  "to": "b8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: veža na b3, mat na b8.",
    "solution": "Rb3+ Kh8 Rb8#"
  },
  {
    "weekIndex": 5,
    "difficulty": "medium",
    "estimatedRating": 1721,
    "fen": "6k1/5ppp/8/8/8/8/4Q3/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "e2",
          "to": "d3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "d3",
                  "to": "d8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qd3+ a doraz na d8.",
    "solution": "Qd3+ Kh8 Qd8#"
  },
  {
    "weekIndex": 5,
    "difficulty": "hard",
    "estimatedRating": 2068,
    "fen": "5rk1/5ppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "e3"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f8",
              "to": "e8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e3",
                  "to": "d4"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "e8",
                      "to": "f8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "d4",
                          "to": "c5"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "f8",
                              "to": "c8"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "c5",
                                  "to": "c8"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v štyroch bielych ťahoch: dáma obchádza vežu na c8.",
    "solution": "Qe3+ Re8 Qd4+ Rf8 Qc5+ Rc8 Qxc8#"
  },
  {
    "weekIndex": 6,
    "difficulty": "easy",
    "estimatedRating": 1509,
    "fen": "6k1/5ppp/8/8/8/8/3Q4/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "d2",
          "to": "c3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c3",
                  "to": "c8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: úvod dámou (Qc3+, Qd3+ …) — po obrane čierneho dajte mat akýmkoľvek správnym ťahom.",
    "solution": "Qc3+ Kh8 Qc8#"
  },
  {
    "weekIndex": 6,
    "difficulty": "medium",
    "estimatedRating": 1764,
    "fen": "6k1/5ppp/8/8/8/5N2/5QPP/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f3",
          "to": "e5"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "f8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f2",
                  "to": "f7"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Kombinácia jazdca a dámy: Ne5 a Qxf7#.",
    "solution": "Ne5+ Kf8 Qxf7#"
  },
  {
    "weekIndex": 6,
    "difficulty": "hard",
    "estimatedRating": 2123,
    "fen": "6k1/8/8/8/4q3/8/8/3R2K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "d1",
          "to": "d2"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "e4",
              "to": "d5"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "d2",
                  "to": "d5"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Získajte dámu: Rd2 a po Qd5 výměna na d5.",
    "solution": "Rd2 Qd5 Rxd5"
  },
  {
    "weekIndex": 7,
    "difficulty": "easy",
    "estimatedRating": 1541,
    "fen": "6k1/5ppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "e3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e3",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qe3+ a mat na e8 (nie útok na f7).",
    "solution": "Qe3+ Kh8 Qe8#"
  },
  {
    "weekIndex": 7,
    "difficulty": "medium",
    "estimatedRating": 1806,
    "fen": "2r2k2/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b7"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "d8",
                      "to": "e8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "f2",
                          "to": "f7"
                        },
                        "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                        "accept": "checkmate"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Stredná kombinácia: Rb4–Rb7 a mat dámou.",
    "solution": "Rb4 Rd8 Rb7+ Re8 Qxf7#"
  },
  {
    "weekIndex": 7,
    "difficulty": "hard",
    "estimatedRating": 2177,
    "fen": "6k1/8/8/4N3/5q2/8/8/2R3K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "e5",
          "to": "c6"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f4",
              "to": "e5"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c6",
                  "to": "e5"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Jazdec na c6, po Qe5 zoberte dámu jazdcom.",
    "solution": "Nc6 Qe5 Nxe5"
  },
  {
    "weekIndex": 8,
    "difficulty": "easy",
    "estimatedRating": 1573,
    "fen": "6k1/4pppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "d4"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "d4",
                  "to": "d8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qd4+ a mat na d8 (oslabené pešiaky f7–h7).",
    "solution": "Qd4+ Kh8 Qd8#"
  },
  {
    "weekIndex": 8,
    "difficulty": "medium",
    "estimatedRating": 1849,
    "fen": "6k1/8/8/8/8/4q3/8/2R3K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "g1",
          "to": "g2"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "e3",
              "to": "c5"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c1",
                  "to": "c5"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Kráľ na g2 pripraví Rxc5 po Qc5.",
    "solution": "Kg2 Qc5 Rxc5"
  },
  {
    "weekIndex": 8,
    "difficulty": "hard",
    "estimatedRating": 2232,
    "fen": "6k1/8/8/8/8/5q2/8/2R3K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "c1",
          "to": "c2"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f3",
              "to": "c6"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c2",
                  "to": "c6"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Získajte dámu: Rc2 a výměna po Qc6.",
    "solution": "Rc2 Qc6 Rxc6"
  },
  {
    "weekIndex": 9,
    "difficulty": "easy",
    "estimatedRating": 1605,
    "fen": "6k1/5ppp/8/8/8/8/7R/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "h2",
          "to": "e2"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e2",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: veža z h2 na e2 a Re8#.",
    "solution": "Re2+ Kh8 Re8#"
  },
  {
    "weekIndex": 9,
    "difficulty": "medium",
    "estimatedRating": 1892,
    "fen": "6k1/5ppp/8/8/8/8/2Q5/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "c2",
          "to": "b3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b3",
                  "to": "b8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qb3+ a mat na b8.",
    "solution": "Qb3+ Kh8 Qb8#"
  },
  {
    "weekIndex": 9,
    "difficulty": "hard",
    "estimatedRating": 2286,
    "fen": "5rk1/5ppp/8/8/8/8/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "e3"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f8",
              "to": "e8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e3",
                  "to": "d4"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "e8",
                      "to": "f8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "d4",
                          "to": "c5"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "f8",
                              "to": "c8"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "c5",
                                  "to": "c8"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Štvorťahová dámska kombinácia proti čiernej veži.",
    "solution": "Qe3+ Re8 Qd4+ Rf8 Qc5+ Rc8 Qxc8#"
  },
  {
    "weekIndex": 10,
    "difficulty": "easy",
    "estimatedRating": 1636,
    "fen": "6k1/5ppp/8/8/8/8/5Q2/4K3 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f2",
          "to": "f7"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f7",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qxf7+ a mat na e8 (kráľ na e4).",
    "solution": "Qxf7+ Kh8 Qe8#"
  },
  {
    "weekIndex": 10,
    "difficulty": "medium",
    "estimatedRating": 1935,
    "fen": "6k1/5ppp/8/8/8/8/1R6/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b2",
          "to": "b3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b3",
                  "to": "b8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Rb3+ a mat vežou na b8.",
    "solution": "Rb3+ Kh8 Rb8#"
  },
  {
    "weekIndex": 10,
    "difficulty": "hard",
    "estimatedRating": 2341,
    "fen": "6k1/8/8/4N3/5q2/8/8/2R3K1 w - - 0 1",
    "win": "black_queen_captured",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "e5",
          "to": "c6"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "f4",
              "to": "e5"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "c6",
                  "to": "e5"
                },
                "wrong": "Týmto ťahom nezoberiete čiernu dámu.",
                "accept": "black_queen_captured"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Najťažšia: jazdec na c6 a zisk dámy po Qe5.",
    "solution": "Nc6 Qe5 Nxe5"
  },
  {
    "weekIndex": 11,
    "difficulty": "easy",
    "estimatedRating": 1668,
    "fen": "6k1/5ppp/8/8/8/8/4Q3/5K2 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "e2",
          "to": "d3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "d3",
                  "to": "d8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Qd3+ a mat na d8 (kráľ na f5).",
    "solution": "Qd3+ Kh8 Qd8#"
  },
  {
    "weekIndex": 11,
    "difficulty": "medium",
    "estimatedRating": 1977,
    "fen": "6k1/5ppp/8/8/8/8/6R1/5K2 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "g2",
          "to": "e2"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "e2",
                  "to": "e8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Mat v dvoch: Re2+ a Re8# pri kráľovi na f5.",
    "solution": "Re2+ Kh8 Re8#"
  },
  {
    "weekIndex": 11,
    "difficulty": "hard",
    "estimatedRating": 2395,
    "fen": "2r1k3/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b5"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "d8",
                      "to": "d7"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "b5",
                          "to": "b7"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "d7",
                              "to": "d8"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "f2",
                                  "to": "f7"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Pred finále: veža obchádza Rd7, rozhoduje Qxf7#.",
    "solution": "Rb4 Rd8 Rb5 Rd7 Rb7 Rd8 Qxf7#"
  },
  {
    "weekIndex": 12,
    "difficulty": "easy",
    "estimatedRating": 1700,
    "fen": "6k1/5ppp/8/8/8/8/6Q1/5K2 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "g2",
          "to": "f3"
        },
        "wrong": "Tento ťah nevedie k matu v dvoch — skúste iný úvod.",
        "accept": "mate_in_2_opening"
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "h8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f3",
                  "to": "a8"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Záverečný týždeň: Qf3+ a vzdialený mat Qa8#.",
    "solution": "Qf3+ Kh8 Qa8#"
  },
  {
    "weekIndex": 12,
    "difficulty": "medium",
    "estimatedRating": 2020,
    "fen": "6k1/5ppp/8/8/8/5N2/5QPP/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "f3",
          "to": "e5"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "g8",
              "to": "f8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "f2",
                  "to": "f7"
                },
                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                "accept": "checkmate"
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Kombinácia jazdca a dámy — finále festivalu.",
    "solution": "Ne5+ Kf8 Qxf7#"
  },
  {
    "weekIndex": 12,
    "difficulty": "hard",
    "estimatedRating": 2450,
    "fen": "2r2k2/5ppp/8/8/8/1R6/5Q2/6K1 w - - 0 1",
    "win": "checkmate",
    "play": [
      {
        "who": "user",
        "suggest": {
          "from": "b3",
          "to": "b4"
        },
        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
      },
      {
        "who": "bot",
        "pick": "main",
        "choices": [
          {
            "move": {
              "from": "c8",
              "to": "d8"
            },
            "main": true,
            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
            "then": [
              {
                "who": "user",
                "suggest": {
                  "from": "b4",
                  "to": "b5"
                },
                "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
              },
              {
                "who": "bot",
                "pick": "main",
                "choices": [
                  {
                    "move": {
                      "from": "d8",
                      "to": "e8"
                    },
                    "main": true,
                    "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                    "then": [
                      {
                        "who": "user",
                        "suggest": {
                          "from": "b5",
                          "to": "b7"
                        },
                        "wrong": "Týmto ťahom nepostupujete správne — skúste iný biely ťah."
                      },
                      {
                        "who": "bot",
                        "pick": "main",
                        "choices": [
                          {
                            "move": {
                              "from": "e8",
                              "to": "e6"
                            },
                            "main": true,
                            "hint": "Počítač odohral hlavnú obranu — pokračujte podľa plánu.",
                            "then": [
                              {
                                "who": "user",
                                "suggest": {
                                  "from": "f2",
                                  "to": "f7"
                                },
                                "wrong": "Týmto ťahom nedáte mat — skúste iný finiš.",
                                "accept": "checkmate"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ],
    "subtitle": "Majstrovská úloha: sedem ťahov na dvoch vežiach, finiš Qxf7#.",
    "solution": "Rb4 Rd8 Rb5 Re8 Rb7 Re6 Qxf7#"
  }
];
